version: '3'
services:
    timbanh-nginx:
        ports:
            - "80:80"
            - "443:443"
        container_name: timbanh-nginx
        restart: always
        image: nginx:latest
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./private.key:/etc/nginx/ssl/private.key
            - ./bundle.crt:/etc/nginx/ssl/bundle.crt
        links:
            - timbanh-web
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M
    timbanh-web:
        container_name: timbanh-web
        restart: always
        image: timbanh-web-img:1.0.0
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M

